package View;

import Controller.*;

public class DashboardCus extends ViewController {

    public DashboardCus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnStatusOrder = new javax.swing.JButton();
        btn_Kalkulator = new javax.swing.JButton();
        btn_Order = new javax.swing.JButton();
        btn_Kembali = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(785, 520));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Keluar");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(357, 420, 70, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Status Order");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 285, 107, 35);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Kalkulator Laundry");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(307, 286, 180, 35);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Order to Pick");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(577, 286, 130, 35);

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Tugas\\Semester 3\\Pemrograman Berorientasi Objek\\Laundry\\src\\Image\\dashboardCustomer.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 788, 490);

        btnStatusOrder.setBackground(new java.awt.Color(0, 204, 204));
        btnStatusOrder.setFont(new java.awt.Font("Stencil Std", 1, 14)); // NOI18N
        btnStatusOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnStatusOrder.setText("Status Order");
        btnStatusOrder.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        btnStatusOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatusOrderActionPerformed(evt);
            }
        });
        getContentPane().add(btnStatusOrder);
        btnStatusOrder.setBounds(40, 280, 210, 50);

        btn_Kalkulator.setBackground(new java.awt.Color(255, 153, 153));
        btn_Kalkulator.setFont(new java.awt.Font("Stencil Std", 1, 14)); // NOI18N
        btn_Kalkulator.setForeground(new java.awt.Color(255, 255, 255));
        btn_Kalkulator.setText("Kalkulator laundry");
        btn_Kalkulator.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));
        btn_Kalkulator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KalkulatorActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Kalkulator);
        btn_Kalkulator.setBounds(280, 280, 220, 50);

        btn_Order.setBackground(new java.awt.Color(255, 153, 0));
        btn_Order.setFont(new java.awt.Font("Stencil Std", 1, 14)); // NOI18N
        btn_Order.setForeground(new java.awt.Color(255, 255, 255));
        btn_Order.setText("order to pick up");
        btn_Order.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        btn_Order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OrderActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Order);
        btn_Order.setBounds(530, 280, 220, 50);

        btn_Kembali.setBackground(new java.awt.Color(102, 0, 102));
        btn_Kembali.setFont(new java.awt.Font("Swis721 BlkCn BT", 1, 18)); // NOI18N
        btn_Kembali.setForeground(new java.awt.Color(255, 255, 255));
        btn_Kembali.setText("KEMBALI");
        btn_Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Kembali);
        btn_Kembali.setBounds(310, 420, 170, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Keluar");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(357, 420, 70, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_KalkulatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KalkulatorActionPerformed
        openFrame("kalkulator_customer");
    }//GEN-LAST:event_btn_KalkulatorActionPerformed

    private void btn_OrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OrderActionPerformed
        
    }//GEN-LAST:event_btn_OrderActionPerformed

    private void btn_KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KembaliActionPerformed
        getUserController().logout();
        openFrame("login");
    }//GEN-LAST:event_btn_KembaliActionPerformed

    private void btnStatusOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatusOrderActionPerformed
        
    }//GEN-LAST:event_btnStatusOrderActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStatusOrder;
    private javax.swing.JButton btn_Kalkulator;
    private javax.swing.JButton btn_Kembali;
    private javax.swing.JButton btn_Order;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
