/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author kimi reza
 */
public class ItemBaju extends javax.swing.JFrame {

    /**
     * Creates new form ItemBaju
     */
    public ItemBaju() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputBerat = new javax.swing.JTextField();
        cbxJenis = new javax.swing.JComboBox<>();
        inputWaktu = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        inputBerat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBeratActionPerformed(evt);
            }
        });
        getContentPane().add(inputBerat);
        inputBerat.setBounds(440, 170, 170, 40);

        cbxJenis.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbxJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kering", "Setrika", "Basah", " " }));
        cbxJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxJenisActionPerformed(evt);
            }
        });
        getContentPane().add(cbxJenis);
        cbxJenis.setBounds(440, 240, 170, 50);

        inputWaktu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputWaktuActionPerformed(evt);
            }
        });
        getContentPane().add(inputWaktu);
        inputWaktu.setBounds(440, 320, 170, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ITEM BAJU.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 790, 490);

        btnBack.setText("jButton1");
        getContentPane().add(btnBack);
        btnBack.setBounds(20, 430, 230, 50);

        btnTambah.setText("jButton2");
        getContentPane().add(btnTambah);
        btnTambah.setBounds(530, 430, 240, 50);

        setSize(new java.awt.Dimension(804, 498));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputWaktuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputWaktuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputWaktuActionPerformed

    private void inputBeratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBeratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputBeratActionPerformed

    private void cbxJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxJenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxJenisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemBaju.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemBaju.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemBaju.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemBaju.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemBaju().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cbxJenis;
    private javax.swing.JTextField inputBerat;
    private javax.swing.JTextField inputWaktu;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
